# Generated by Django 5.0 on 2023-12-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='profile_pictures/'),
        ),
    ]
